// Generated by Skyright Intake metadata sync. Do not edit by hand.

export type JobNimbusStatusName = "Active" | "Approved" | "Appt Scheduled" | "Contract Sent" | "Draft" | "Estimate Info Gathered" | "Installation WIP" | "Lead" | "Lost" | "New" | "New Bid" | "Plan Review" | "Production - Long Term Sched" | "Production - Mats Ordered" | "Production Scheduled" | "Project Closed Out" | "RFI" | "Sent" | "Sent To Production" | "Signed Contract" | "T/O to Production" | "Webform";
export type JobNimbusWorkflowStageName = string;

export interface JobNimbusField {
  id?: string;
  name?: string;
  label?: string;
  type?: string;
  types?: string[];
  required?: boolean;
  options?: string[];
  observed_count?: number;
  source?: string;
}

export interface JobNimbusMetadataSnapshot {
  synced_at: string;
  job_fields: JobNimbusField[];
  contact_fields: JobNimbusField[];
  work_order_fields: JobNimbusField[];
  estimate_fields: JobNimbusField[];
  dropdown_values: Record<string, unknown>[];
  statuses: Record<string, unknown>[];
  workflow_stages: Record<string, unknown>[];
  source?: string;
}
